global:
  podSecurityContext:
    runAsUser: 10123456
    runAsGroup: 20987654

cube:
  server:
    service:
      type: NodePort
      nodePort: 32000
    podAnnotations:
      linkerd.io/inject: enabled
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
  config:
    GUNICORN_CMD_ARGS: "--workers=4 --timeout=3600"

postgresql:
  primary:
    podAnnotations:
      linkerd.io/inject: enable
    service:
      annotations:
        config.linkerd.io/opaque-ports: "5432"

pfcon:
  storage:
    size: 10Gi

pfdcm:
  enabled: true
  service:
    type: NodePort
    nodePort: 32001
  podAnnotations:
    linkerd.io/inject: enabled
  listener:
    service:
      type: NodePort
      nodePort: 32004
    config:
      verbose: true
      promiscuous: true
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=oxidicom
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-opentelemetry-collector.observe.svc.cluster.local:4317
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 2Gi

orthanc:
  enabled: true
  service:
    type: NodePort
    nodePort: 32003
  config:
    dicomModalities:
      "ChRIS": [ "ChRIS", "cacao-oxidicom", 11111 ]
    registeredUsers:
      orthanc: orthanc
